title: Coderatul
description: This is a static website
social_link: github.com/coderatul
social_username: coderatul
github_repo: Atulkushwaha
github_username: broccolini
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /atulkushwaha
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
